### ISSUE TITLE
Management Intern panel

### ISSUE THREAD

**Issue by ondra789987** [bloxstreet/support#4]
Hi,
As a Management Intern, I can see the staff panel. In the panel, I see only 1 button- Messages.
Howewer, when I press the "Messages" button, it won't open anything.

https://gyazo.com/f0b2ed442069721952226fbf025d83a3 (I am pressing it though you can't see it)

**Comment by TheCakeChicken** [comment]
This is not the place to report store bugs. This is for bugs and suggestions relating to the support.bloxstreet.store website only.

**Comment by HOTBOU1111** [comment]
Ye
